version: '3.7'

services:
  node-app:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
      target: dev
    env_file:
      - .env
    restart: always
    volumes:
      - ./:/app
