version: '3'
services:
  node-app:
    image: node:20.8.0
    working_dir: /app
    volumes:
      - ./:/app
    command: ["npm", "start"]
    depends_on:
      database:
        condition: service_healthy
