version: '3'
services:
  database:
    image: mariadb:11.1.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ted_node_monitor
      MYSQL_USER: monitor
      MYSQL_PASSWORD: monitor
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "/usr/local/bin/healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      interval: 2s
      retries: 120

  node-app:
    image: oven/bun:1.0.7-alpine
    working_dir: /app
    restart: always
    volumes:
      - ./:/app
    command: ["bun", "start:watch"]
    ports:
      - "3002:3002"
    depends_on:
      - "database"

volumes:
  mariadb_data:
