name: "API: Build & Deploy"

defaults:
  run:
    working-directory: "api"

on:
  workflow_dispatch: ~
  push:
    tags:
      - 'api-v*'

jobs:
  build:
    name: "Build Image"
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Extract Tag Name
        id: tag
        run: |
          # Extract the tag name from the github.ref context variable
          FULL_TAG="${{ github.ref }}"
          TAG_NAME="${FULL_TAG#refs/tags/api-}"
          echo "Tag Name: $TAG_NAME"
          echo "::set-output name=tag::$TAG_NAME"

      - name: Log in to Docker Hub
        uses: docker/login-action@b4bedf8053341df3b5a9f9e0f2cf4e79e27360c6
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@879dcbb708d40f8b8679d4f7941b938a086e23a7
        with:
          images: joshlopes/tedcrypto-node-monitor-api

      - name: Build and push Docker image
        uses: docker/build-push-action@fdf7f43ecf7c1a5c7afe936410233728a8c2d9c2
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            joshlopes/tedcrypto-node-monitor-api:latest
            joshlopes/tedcrypto-node-monitor-api:${{ steps.tag.outputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
      name: "Deploy to Akash"
      uses: TedcryptoOrg/akash-deploy-action/.github/workflows/deploy.yml@main
      needs: build
      with:
        PROJECT_PATH: "api"
        project_name: "api"
        image: joshlopes/tedcrypto-node-monitor-api:${{ needs.build.outputs.tag }}
      secrets:
        SEED: ${{ secrets.API_WALLET_SEED }}
        PASSWORD: ${{ secrets.AKASH_KEYRING_PASSWORD }}
        ghcr-token: ${{ secrets.GITHUB_TOKEN }}
