name: "API: Deploy"

defaults:
  run:
    working-directory: "api"

on:
  workflow_dispatch: ~
  pull_request: #TODO: just to test, remove later
    paths:
      - ".github/workflows/api.deploy.yaml"
      - "api/**"
  push:
      paths:
        - ".github/workflows/api.deploy.yaml"
        - "api/**"
      branches:
        - "main"

concurrency:
  group: ${{ github.head_ref || github.run_id }} ~ "api.deploy.yaml"
  cancel-in-progress: true

jobs:
  deploy:
    uses: TedcryptoOrg/akash-deploy-action/.github/workflows/deploy.yml@make-deploy-sharable
    with:
      PROJECT_PATH: "api"
      project_name: "api"
    secrets:
      SEED: ${{ secrets.API_WALLET_SEED }}
      PASSWORD: ${{ secrets.AKASH_KEYRING_PASSWORD }}
      ghcr-token: ${{ secrets.GITHUB_TOKEN }}
