name: "Frontend: Build (Next)"

defaults:
  run:
    working-directory: "frontend"

on:
  workflow_dispatch: ~
  pull_request:
    paths:
      - ".github/workflows/frontend.build-image.yaml"
      - "frontend/**"
  push:
    paths:
      - ".github/workflows/frontend.build-image.yaml"
      - ".github/workflows/frontend.deploy.yaml"
      - "frontend/**"
    tags:
      - 'frontend-v*'
    branches:
      - "main"

jobs:
  build:
    name: "Build Image"
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Extract Tag Name or SHA for Main Branch
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/frontend-v')
        id: tag
        run: |
          FULL_TAG="${{ github.ref }}"
          # Replace slashes with hyphens and remove 'refs/tags/frontend-' prefix
          SANITIZED_TAG="${FULL_TAG/refs\/heads\//}"
          SANITIZED_TAG="${SANITIZED_TAG/refs\/tags\/frontend-/}"
          SANITIZED_TAG="${SANITIZED_TAG/\//-}"
          if [ -z "$SANITIZED_TAG" ] || [ "$SANITIZED_TAG" == "main" ]; then
            SANITIZED_TAG="latest"
          fi
          echo "Sanitized Tag Name: $SANITIZED_TAG"
          echo "::set-output name=tag::$SANITIZED_TAG"

      - name: Set SHA for Pull Request
        if: github.event_name == 'pull_request'
        id: sha
        run: |
          PR_HEAD_SHA="${{ github.event.pull_request.head.sha }}"
          echo "SHA: $PR_HEAD_SHA"
          echo "::set-output name=sha::$PR_HEAD_SHA"

      - name: Log in to Docker Hub
        uses: docker/login-action@5f4866a30a54f16a52d2ecb4a3898e9e424939cf
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@1294d94f8ee362ab42b6da04c35f4cd03a0e6af7
        with:
          images: joshlopes/tedcrypto-node-monitor-frontend-v2

      - name: Build and push Docker image
        uses: docker/build-push-action@7e6f77677b7892794c8852c6e3773c3e9bc3129a
        with:
          context: ./frontend
          file: ./frontend/docker/Dockerfile
          push: true
          provenance: false
          load: false
          tags: |
            ${{ (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/frontend-v')) && format('joshlopes/tedcrypto-node-monitor-frontend-v2:{0}', steps.tag.outputs.tag) || '' }}
            ${{ github.event_name == 'pull_request' && format('joshlopes/tedcrypto-node-monitor-frontend-v2:pr-{0}', steps.sha.outputs.sha) || '' }}
          labels: ${{ steps.meta.outputs.labels }}
