name: "Frontend: Build"

defaults:
  run:
    working-directory: "ui"

on:
  workflow_dispatch: ~
  pull_request:
    paths:
      - ".github/workflows/frontend.build-image.yaml"
      - "ui/**"
  push:
    paths:
      - ".github/workflows/frontend.build-image.yaml"
      - ".github/workflows/frontend.deploy.yaml"
      - "ui/**"
    tags:
      - 'frontend-v*'
    branches:
      - "main"

jobs:
  build:
    name: "Build Image"
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Extract Tag Name or SHA for Main Branch
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/frontend-v')
        id: tag
        run: |
          FULL_TAG="${{ github.ref }}"
          # Replace slashes with hyphens and remove 'refs/tags/frontend-' prefix
          SANITIZED_TAG="${FULL_TAG/refs\/heads\//}"
          SANITIZED_TAG="${SANITIZED_TAG/refs\/tags\/frontend-/}"
          SANITIZED_TAG="${SANITIZED_TAG/\//-}"
          if [ -z "$SANITIZED_TAG" ] || [ "$SANITIZED_TAG" == "main" ]; then
            SANITIZED_TAG="latest"
          fi
          echo "Sanitized Tag Name: $SANITIZED_TAG"
          echo "::set-output name=tag::$SANITIZED_TAG"

      - name: Set SHA for Pull Request
        if: github.event_name == 'pull_request'
        id: sha
        run: |
          PR_HEAD_SHA="${{ github.event.pull_request.head.sha }}"
          echo "SHA: $PR_HEAD_SHA"
          echo "::set-output name=sha::$PR_HEAD_SHA"

      - name: Log in to Docker Hub
        uses: docker/login-action@7ca345011ac4304463197fac0e56eab1bc7e6af0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@8e1d5461f02b7886d3c1a774bfbd873650445aa2
        with:
          images: joshlopes/tedcrypto-node-monitor-frontend

      - name: Build and push Docker image
        uses: docker/build-push-action@31ca4e5d51253d7e4a2317bfe74699cbe3a398a9
        with:
          context: ./ui
          build-args: |
            "REACT_APP_API_HOST=${{ secrets.REACT_APP_API_HOST }}"
          file: ./ui/docker/Dockerfile
          push: true
          provenance: false
          load: false
          tags: |
            ${{ (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/frontend-v')) && format('joshlopes/tedcrypto-node-monitor-frontend:{0}', steps.tag.outputs.tag) || '' }}
            ${{ github.event_name == 'pull_request' && format('joshlopes/tedcrypto-node-monitor-frontend:pr-{0}', steps.sha.outputs.sha) || '' }}
            ${{ github.event_name == 'pull_request' && format('joshlopes/tedcrypto-node-monitor-frontend:pr-{0}', github.event.pull_request.number) || '' }}
          labels: ${{ steps.meta.outputs.labels }}
