name: "Frontend: Deploy (Next)"

on:
  workflow_run:
    workflows: ["Frontend: Build (Next)"]
    types:
      - completed

jobs:
  deploy:
    name: "Deploy Image"
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Image to CapRrover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: "${{ secrets.CAPROVER_SERVER }}"
          app: "${{ secrets.CAPROVER_FRONTEND_APP_V2 }}"
          token: "${{ secrets.CAPROVER_FRONTEND_TOKEN_V2 }}"
          image: "joshlopes/tedcrypto-node-monitor-frontend-v2:latest"

      - name: 'Send message'
        uses: ./.github/actions/send-telegram-message
        with:
          bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          thread_id: ${{ secrets.TELEGRAM_THREAD_ID }}
          message: |
            Node Monitor Frontend V2 deployed successfully!
            ${{ github.actor }}: ${{ github.event.commits[0].message }}
            
            **Changes**: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            **Deployment**: ${{ secrets.CAPROVER_SERVER }}/#/apps/details/${{ secrets.CAPROVER_FRONTEND_APP }}
