name: "Monitor: Tests"

defaults:
  run:
    working-directory: "monitor"

on:
  workflow_dispatch: ~
  pull_request:
    paths:
      - ".github/workflows/monitor.tests.yaml"
      - "monitor/**"
  push:
    paths:
      - ".github/workflows/monitor.tests.yaml"
      - "monitor/**"
    branches:
      - "main"

permissions:
  contents: read

concurrency:
  group: ${{ github.head_ref || github.run_id }} ~ "monitor.tests.yaml"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install modules
        run: npm install

      - name: Run Tests
        run: npm run test
