name: "Shared: Labeler"

on:
  - "pull_request_target"

jobs:
  triage:
    name: "Triage"
    runs-on: "ubuntu-latest"

    permissions:
      contents: "read"
      pull-requests: "write"

    steps:
      - uses: "actions/labeler@v4"
        with:
          configuration-path: ".github/labeler.yaml"
          sync-labels: true
