name: "Static analysis"

on: [push]

permissions:
  contents: read

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install modules
        run: npm install

      - name: Run Lint
        run: npm run lint
